import {evaluateExpression,evaluateComplexExpression,evaluateBaseExpression,formatted,fractionOf,integrate,differentiate,parseMatrix,transpose,multiplyMatrices,determinant,inverse,parseVector,vectorOperation,statistics,solvePolynomial,complexOperation,constants,units,convertUnits} from './calc-engine.js';
import {equationTypes,equationSlots,solveSelectedEquation} from './equation-engine.js';

export function initCalculator(s){s.calcPanel??='display';s.calcMode??='COMP';s.calcAngle??='RAD';s.calcShift??=false;s.calcAlpha??=false;s.calcHyp??=false;s.calcFraction??=false;s.calcInsertMode??=true;s.calcMemory??=0;s.calcVariables??={A:0,B:0,C:0,D:0,E:0,F:0,X:0,Y:0,M:0};s.calcPending??='';s.calcTool??='Integration';s.calcToolResult??='';s.calcInputs??={};s.calcHistory??=[];s.calcExpression??='';s.calcAnswer??='0';s.calcCursor??=s.calcExpression.length;s.calcMenuIndex??=0;s.calcReplayIndex??=-1;s.calcTemplate??=null;s.calcSearch??='';s.calcBase??='DEC';s.calcBaseBlock??=0;s.calcEquation??={type:null,values:[],index:0,cursor:0,solutions:[],solutionIndex:0};s.calcStatements??=null}
const modes=['COMP','CPLX','STAT','BASE','EQN','TABLE','MATX','VCTR'];
const apps=[['Scientific Constants','π'],['Metric Conversions','⇄'],['Integration','∫'],['Differentiation','d/dx'],['Matrix','▦'],['Vector','⬡'],['Statistics','▥'],['Trigonometry','△'],['Complex Numbers','ℂ'],['Equation Solver','x²'],['Table','≡'],['Memory / Recall','M'],['History','↶']];
// Labels and their actions share a single map. Empty alternate labels are deliberately unassigned.
export const calculatorKeys={
  Mode:{shift:'SET UP'},CONV:{shift:'C-VALUE'},CALC:{shift:'Solve',alpha:'='},'x⁻¹':{shift:'x!',alpha:':'},'∫dx':{shift:'d/dx',mode:'∠'},ENG:{shift:'←ENG',alpha:'i'},
  'a/b':{shift:'a b/c',mode:'DEC'},'√(':{shift:'∛(',mode:'HEX'},'xʸ':{shift:'ⁿ√(',mode:'BIN'},'x²':{shift:'x³',mode:'OCT'},'log(':{shift:'10ˣ',alpha:'log□'},'ln(':{shift:'eˣ',mode:'◀BLK'},
  '(-)':{alpha:'A'},'°′″':{shift:'PFact',alpha:'B'},hyp:{alpha:'C'},'sin(':{shift:'sin⁻¹',alpha:'D'},'cos(':{shift:'cos⁻¹',alpha:'E'},'tan(':{shift:'tan⁻¹',alpha:'F'},
  RCL:{shift:'STO'},'(':{shift:'%'},')':{shift:',',alpha:'X'},'F↔D':{alpha:'Y'},'M+':{shift:'M−',alpha:'M'},
  '9':{shift:'CLR'},DEL:{shift:'Insert'},CA:{shift:'OFF'},'×':{shift:'nPr'},'÷':{shift:'nCr'},'+':{shift:'Pol('},'−':{shift:'Rec('},
  '0':{shift:'ROUND'},'.':{shift:'Rand',alpha:'iRand'},EXP:{shift:'π',alpha:'e'},Ans:{shift:'DRG▶'}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(s,key,label,placeholder,kind='text')=>`<label class="field">${label}<input type="${kind}" data-calc-field="${key}" value="${esc(s.calcInputs[key]||'')}" placeholder="${esc(placeholder)}"></label>`;
const numberField=(s,key,label,placeholder)=>field(s,key,label,placeholder,'number');
const result=s=>s.calcToolResult?`<div class="calc-tool-result" role="status"><span class="overline">RESULT</span><strong>${esc(s.calcToolResult)}</strong></div>`:'';
const displayedAnswer=s=>{let n=Number(s.calcAnswer);if(!s.calcFraction||!Number.isFinite(n))return String(s.calcAnswer);let value=fractionOf(n);if(!s.calcMixedFraction||!value.includes('/'))return value;let [top,bottom]=value.split('/').map(Number),whole=Math.trunc(top/bottom),remainder=Math.abs(top%bottom);return whole&&remainder?`${whole} ${remainder}/${bottom}`:value};
const matrixText=m=>m.map(row=>row.map(formatted).join('  ')).join('  /  ');
const textbook=s=>esc(s).replace(/(pi|\d+(?:\.\d+|\^\d+)?)\/(\d+(?:\.\d+)?)/g,(_,a,b)=>`<span class="textbook-fraction"><span>${a==='pi'?'π':a}</span><span>${b}</span></span>`).replace(/\^\((-?\d+)\)/g,(_,n)=>`<sup>${n}</sup>`).replace(/\^(-?\d+)/g,(_,n)=>`<sup>${n}</sup>`).replace(/sqrt\(/g,'√(').replace(/cbrt\(/g,'∛(').replace(/\bpi\b/g,'π');
const withCursor=(value,cursor,field='expression')=>{let chars=Array.from(value);if(!chars.length)return `<span class="calc-empty-box" data-calc-touch-field="${esc(field)}" data-calc-touch-pos="0">□<span class="calc-insertion">_</span></span>`;let html='';for(let i=0;i<chars.length;i++){let square=chars[i]==='^'&&chars[i+1]==='2',cube=chars[i]==='^'&&chars[i+1]==='3',power=square||cube,display=power?(square?'²':'³'):chars[i];html+=`<span class="calc-edit-char ${i===cursor||power&&i+1===cursor?'selected':''}" data-calc-touch-field="${esc(field)}" data-calc-touch-pos="${i}">${esc(display)}</span>`;if(power)i++}return html+(cursor>=chars.length?`<span class="calc-insertion" data-calc-touch-field="${esc(field)}" data-calc-touch-pos="${chars.length}">_</span>`:'')};
const templateFields={integral:['lower','upper','body'],derivative:['body','at'],fraction:['numerator','denominator'],nthroot:['index','radicand'],power:['base','exponent'],logbase:['base','value'],squareRoot:['radicand'],cubeRoot:['radicand'],tenpow:['exponent'],epow:['exponent']};
function templateView(t){const f=name=>`<span class="calc-template-field ${t.field===name?'active':''}" data-calc-touch-field="${name}" data-calc-touch-pos="${t.fields[name].length}">${t.field===name?withCursor(t.fields[name],t.cursor,name):t.fields[name]?textbook(t.fields[name]):'<span class="calc-empty-box">□</span>'}</span>`;
  if(t.kind==='integral')return `<div class="math-template integral-template"><span class="integral-symbol">∫</span><span class="integral-bounds"><span>${f('upper')}</span><span>${f('lower')}</span></span><span class="integral-body">${f('body')} dx</span></div>`;
  if(t.kind==='derivative')return `<div class="math-template derivative-template"><span>d/dx</span><span>${f('body')}</span><span class="derivative-at">x = ${f('at')}</span></div>`;
  if(t.kind==='fraction')return `<div class="math-template fraction-template"><span class="fraction-stack"><span>${f('numerator')}</span><span>${f('denominator')}</span></span></div>`;
  if(t.kind==='power')return `<div class="math-template power-template">${f('base')}<sup>${f('exponent')}</sup></div>`;
  if(t.kind==='nthroot')return `<div class="math-template root-template"><sup>${f('index')}</sup>√<span class="root-radicand">${f('radicand')}</span></div>`;
  if(t.kind==='squareRoot'||t.kind==='cubeRoot')return `<div class="math-template root-template">${t.kind==='cubeRoot'?'∛':'√'}<span class="root-radicand">${f('radicand')}</span></div>`;
  if(t.kind==='tenpow'||t.kind==='epow')return `<div class="math-template power-template">${t.kind==='tenpow'?'10':'e'}<sup>${f('exponent')}</sup></div>`;
  return `<div class="math-template log-template">log<sub>${f('base')}</sub>(${f('value')})</div>`}
const keyButton=(s,key,extra='')=>{let labels=calculatorKeys[key]||{},active=s.calcShift&&labels.shift||s.calcAlpha&&labels.alpha||s.calcMode==='BASE'&&labels.mode;return `<span class="key-wrap ${active?'alternate-ready':''}"><span class="key-legends"><span class="key-shift">${esc(labels.shift||'')}</span><span class="key-alpha">${esc(labels.alpha||'')}</span><span class="key-mode">${esc(labels.mode||'')}</span></span><button class="physical-key ${extra}" data-key="${esc(key)}" aria-label="${esc(key)}${labels.shift?', Shift '+labels.shift:''}${labels.alpha?', Alpha '+labels.alpha:''}${labels.mode?', mode '+labels.mode:''}">${esc(key)}</button></span>`};

export function calculatorView(s,{overlay=false}={}){initCalculator(s);
  const upper=(key,area)=>`<span class="upper-position" style="grid-area:${area}">${keyButton(s,key,`upper-key ${key==='Shift'?'shift-key':key==='Alpha'?'alpha-key':key==='Apps'?'apps-key':''} ${key==='Shift'&&s.calcShift||key==='Alpha'&&s.calcAlpha?'latched':''}`)}</span>`;
  const scientific=['a/b','√(','xʸ','x²','log(','ln(','(-)','°′″','hyp','sin(','cos(','tan(','RCL','Abs(','(',')','F↔D','M+'];
  const numeric=['7','8','9','DEL','CA','4','5','6','×','÷','1','2','3','+','−','0','.','EXP','Ans','='];
  return `<div class="calculator-device ${overlay?'calculator-compact':''}" role="group" aria-label="Scientific calculator">
    <div class="device-brand"><strong>ESAS</strong><span>F-789SGA II inspired</span></div>
    <div class="device-lcd ${s.calcPanel==='display'?'':'lcd-menu'}">${internalScreen(s)}</div>
    <div class="upper-keys">
      ${upper('Shift','shift')}${upper('Alpha','alpha')}
      <div class="dpad" aria-label="Four-direction edit pad"><button data-calc-control="up" aria-label="Move up">▲</button><button data-calc-control="left" aria-label="Move left">◀</button><span>✦</span><button data-calc-control="right" aria-label="Move right">▶</button><button data-calc-control="down" aria-label="Move down">▼</button></div>
      ${upper('Mode','mode')}${upper('ON','on')}${upper('Apps','apps')}${upper('CONV','conv')}
      ${upper('CALC','calc')}${upper('x⁻¹','reciprocal')}${upper('∫dx','integral')}${upper('ENG','eng')}
    </div>
    <div class="scientific-row">${scientific.map(k=>keyButton(s,k,'scientific-key')).join('')}</div>
    <div class="numeric-row">${numeric.map(k=>keyButton(s,k,`numeric-key ${k==='='?'equals':''} ${['DEL','CA'].includes(k)?'utility-key':''}`)).join('')}</div>
    <div class="device-foot">${s.calcPending?'Select an Alpha variable · ':''}${s.calcTemplate?'Arrows move across the active math fields':s.calcPanel==='display'?'Arrows edit or replay · Apps, Mode and CONV are on this keypad':'Arrows select · = confirms · CA returns'}</div>
  </div>`
}
function equationView(s){let e=s.calcEquation;if(s.calcPanel==='eqmenu')return `<div class="lcd-title">EQN · Choose equation</div><div class="lcd-eqn-list">${equationTypes.map((item,i)=>`<button class="${i===s.calcMenuIndex?'selected':''}" data-calc-equation="${item.id}"><b>${i+1}</b><span>${esc(item.label)}<small>${esc(item.description)}</small></span></button>`).join('')}</div>`;
  if(s.calcPanel==='eqresult'){let result=e.solutions[e.solutionIndex];return `<div class="lcd-title">${esc(equationTypes.find(x=>x.id===e.type)?.label)} · Solutions</div><div class="lcd-eqn-answer">${esc(result.name)} = ${esc(formatComplexRoot(result.value))}</div><div class="lcd-eqn-progress">${e.solutionIndex+1} of ${e.solutions.length} · arrows to browse</div><button class="lcd-inline-action" data-calc-equation="back">Edit coefficients</button>`}
  let slots=equationSlots(e.type),def=equationTypes.find(x=>x.id===e.type),n=def.variables?.length;return `<div class="lcd-title">EQN · ${esc(def.label)}</div><div class="lcd-eqn-coeffs">${slots.map((label,i)=>`<button class="lcd-coeff ${i===e.index?'selected':''}" data-calc-equation-slot="${i}"><small>${esc(label)}</small><strong>${i===e.index?withCursor(e.values[i],e.cursor,`eq:${i}`):e.values[i]?esc(e.values[i]):'□'}</strong></button>`).join('')}</div><div class="lcd-eqn-progress">${n?`${n} equations · `:''}Field ${e.index+1} of ${slots.length} · = next/solve</div>${String(s.calcAnswer).startsWith('Error')?`<div class="lcd-eqn-error">${esc(s.calcAnswer)}</div>`:''}`}
const formatComplexRoot=([re,im])=>Math.abs(im)<1e-9?formatted(re):`${formatted(re)} ${im<0?'−':'+'} ${formatted(Math.abs(im))}i`;
export function calculatorChooseEquation(s,type){initCalculator(s);if(type==='back'){s.calcPanel='eqedit';return}let slots=equationSlots(type);s.calcMode='EQN';s.calcEquation={type,values:slots.map(()=>''),index:0,cursor:0,solutions:[],solutionIndex:0};panel(s,'eqedit')}
export function calculatorSelectMode(s,mode){initCalculator(s);s.calcMode=mode;s.calcExpression='';s.calcTemplate=null;s.calcCursor=0;let tool={STAT:'Statistics',MATX:'Matrix',VCTR:'Vector',TABLE:'Table'}[mode];if(mode==='EQN')panel(s,'eqmenu');else if(tool){s.calcTool=tool;s.calcToolResult='';panel(s,'tool')}else panel(s,'display')}
export function calculatorTouch(s,field,position){initCalculator(s);let p=Math.max(0,Number(position)||0);if(field.startsWith('eq:')&&s.calcPanel==='eqedit'){let i=Number(field.slice(3)),e=s.calcEquation;if(i>=0&&i<e.values.length){e.index=i;e.cursor=Math.min(p,e.values[i].length)}return}if(s.calcPanel!=='display')return;if(field==='expression'&&!s.calcTemplate){s.calcCursor=Math.min(p,s.calcExpression.length);return}if(s.calcTemplate&&Object.hasOwn(s.calcTemplate.fields,field)){s.calcTemplate.field=field;s.calcTemplate.cursor=Math.min(p,s.calcTemplate.fields[field].length)}}
function internalScreen(s){if(s.calcPower===false)return '<div class="lcd-off">OFF · Press ON</div>';if(['eqmenu','eqedit','eqresult'].includes(s.calcPanel))return equationView(s);if(s.calcPanel==='display')return `<div class="row between"><span class="lcd-indicators">${s.calcShift?'S ':''}${s.calcAlpha?'A ':''}${s.calcPending?esc(s.calcPending)+' ':''}${s.calcHyp?'HYP ':''}${s.calcInsertMode?'':'OVR '}${s.calcAngle} · ${esc(s.calcMode)}${s.calcMode==='BASE'?' · '+s.calcBase:''}${s.calcMemory?' · M':''}</span><span>${s.calcReplayIndex>=0?'↶':''}</span></div><div class="lcd-expression" role="textbox" aria-label="Calculator expression">${s.calcTemplate?templateView(s.calcTemplate):withCursor(s.calcExpression,Math.min(s.calcCursor,s.calcExpression.length))}</div><div class="lcd-result">${esc(displayedAnswer(s))}${s.calcSecondary?`<small class="calc-secondary">${esc(s.calcSecondary)}</small>`:''}</div>`;
  if(s.calcPanel==='apps')return `<div class="lcd-title">Apps / Functions</div>${appsPanel(s)}`;
  if(s.calcPanel==='mode')return `<div class="lcd-title">Select mode</div><div class="lcd-mode-list">${modes.map((m,i)=>`<button class="${i===s.calcMenuIndex?'selected':''}" data-calc-select-mode="${m}">${m}</button>`).join('')}</div>`;
  if(s.calcPanel==='setup')return `<div class="lcd-title">SET UP · Angle</div><div class="lcd-mode-list">${['RAD','DEG','GRAD'].map((m,i)=>`<button class="${i===s.calcMenuIndex?'selected':''}" data-calc-setting="${m}">${m}</button>`).join('')}</div>`;
  if(s.calcPanel==='clear')return `<div class="lcd-title">CLR · Select data to clear</div><div class="lcd-mode-list">${['Expression','Memory','History','All'].map((name,i)=>`<button class="${i===s.calcMenuIndex?'selected':''}" data-calc-clear="${name}">${name}</button>`).join('')}</div>`;
  if(s.calcPanel==='converter')return converter(s);
  if(s.calcPanel==='constants')return constantsPanel(s);
  if(s.calcPanel==='history')return history(s);
  return toolView(s)
}
function appsPanel(s){return `<div class="lcd-app-list">${apps.map(([name,icon],i)=>`<button class="${i===s.calcMenuIndex?'selected':''}" data-calc-tool="${name}"><b>${icon}</b><span>${name}</span><small>${i+1}</small></button>`).join('')}</div>`}
function history(s){return `<h3>Calculation history</h3>${s.calcHistory.length?s.calcHistory.map((h,i)=>`<button class="action-row ${i===s.calcMenuIndex?'selected':''}" data-history="${esc(h.expression)}"><span class="grow"><strong>${esc(h.expression)}</strong><small>= ${esc(h.answer)}</small></span><span class="chev">↗</span></button>`).join(''):'<div class="empty">Calculations you finish will appear here.</div>'}<button class="btn secondary wide" data-calc-op="clear-history">Clear history</button>`}
function converter(s){let category=s.calcInputs.category||'Length',group=units[category],names=Object.keys(group),from=s.calcInputs.from&&names.includes(s.calcInputs.from)?s.calcInputs.from:names[0],to=s.calcInputs.to&&names.includes(s.calcInputs.to)?s.calcInputs.to:names[1];return `<h3>Unit converter</h3><label class="field">Category<select data-calc-field="category">${Object.keys(units).map(k=>`<option ${k===category?'selected':''}>${k}</option>`).join('')}</select></label>${numberField(s,'value','Value','1')}<div class="row"><label class="field grow">From<select data-calc-field="from">${names.map(k=>`<option ${k===from?'selected':''}>${esc(k)}</option>`).join('')}</select></label><button class="icon-btn" data-calc-op="swap-units" aria-label="Swap units">⇄</button><label class="field grow">To<select data-calc-field="to">${names.map(k=>`<option ${k===to?'selected':''}>${esc(k)}</option>`).join('')}</select></label></div><button class="btn wide" data-calc-op="convert">Convert</button>${result(s)}<p class="footnote">Available pairs are calculated from the listed units. The device’s exact 172 conversion mappings have not yet been matched.</p>`}
function constantsPanel(s){let q=s.calcSearch.toLowerCase(),matches=constants.filter(([symbol,name])=>(symbol+' '+name).toLowerCase().includes(q));return `<h3>Scientific constants</h3><label class="search"><span>⌕</span><input data-calc-search placeholder="Search ${constants.length} reference constants" value="${esc(s.calcSearch)}"></label><div class="constant-list">${matches.map(([symbol,name,value,unit])=>`<button class="action-row" data-constant="${value}"><span class="glyph violet">${esc(symbol)}</span><span class="grow"><strong>${esc(name)}</strong><small>${esc(String(value))} ${esc(unit)}</small></span><span class="chev">＋</span></button>`).join('')||'<div class="empty">No matching constants.</div>'}</div><p class="footnote">Selected NIST/CODATA reference values. The exact 79-item device catalog remains to be mapped.</p>`}
function matrixPanel(s){return `<div class="grid2"><button class="tile compact" data-calc-tool="Matrix"><span class="glyph violet">▦</span><h3>Matrix</h3><p>Up to 4×4</p></button><button class="tile compact" data-calc-tool="Vector"><span class="glyph cyan">⬡</span><h3>Vector</h3><p>2D to 4D</p></button></div><p class="footnote">Select a workspace to calculate.</p>`}
export function toolView(s){initCalculator(s);let t=s.calcTool;return `<div class="calc-tool-header"><span class="glyph violet">${apps.find(([name])=>name===t)?.[1]||'∑'}</span><div><div class="overline">APPS / FUNCTIONS</div><h2>${esc(t)}</h2></div></div><div class="glass pad">${toolForm(s,t)}${result(s)}</div>`}
function toolForm(s,t){
  if(t==='Integration'||t==='Differentiation')return `${field(s,'expression','Function of x','e.g. sin(x) or x^2')}${t==='Integration'?`${numberField(s,'a','Lower limit','0')}${numberField(s,'b','Upper limit','3.14159')}`:numberField(s,'point','Evaluate at x','1')}<button class="btn wide" data-calc-op="calculate-tool">Calculate</button><p class="footnote">Numerical ${t.toLowerCase()}; use x as the variable. Results are approximations.</p>`;
  if(t==='Matrix')return `${field(s,'matrixA','Matrix A','1, 2; 3, 4')}${field(s,'matrixB','Matrix B (for A × B)','5, 6; 7, 8')}<div class="chips">${['determinant','inverse','transpose','multiply'].map(op=>`<button class="pill" data-calc-op="matrix-${op}">${op}</button>`).join('')}</div><p class="footnote">Rows are separated by semicolons; entries by commas. Maximum size: 4×4.</p>`;
  if(t==='Vector')return `${field(s,'vectorA','Vector A','1, 2, 3')}${field(s,'vectorB','Vector B','4, 5, 6')}<div class="chips">${['magnitude','dot','cross','add','subtract'].map(op=>`<button class="pill" data-calc-op="vector-${op}">${op}</button>`).join('')}</div>`;
  if(t==='Statistics')return `${field(s,'dataset','Data set','2, 4, 6, 8')}<button class="btn wide" data-calc-op="calculate-tool">Calculate statistics</button>`;
  if(t==='Equation Solver')return `<p class="small muted">Solve ax² + bx + c = 0 (use a = 0 for linear).</p>${numberField(s,'a','a','1')}${numberField(s,'b','b','-3')}${numberField(s,'c','c','2')}<button class="btn wide" data-calc-op="calculate-tool">Solve equation</button>`;
  if(t==='Complex Numbers')return `<p class="small muted">First: a + bi · Second: c + di</p>${['a','b','c','d'].map(k=>numberField(s,k,k,'0')).join('')}<div class="chips">${['add','subtract','multiply','divide'].map(op=>`<button class="pill" data-calc-op="complex-${op}">${op}</button>`).join('')}</div>`;
  if(t==='Table')return `${field(s,'expression','Function of x','x^2 + 1')}${numberField(s,'start','Start x','0')}${numberField(s,'end','End x','5')}${numberField(s,'step','Step','1')}<button class="btn wide" data-calc-op="calculate-tool">Generate table</button>`;
  if(t==='Memory / Recall')return `<p class="muted">Memory: <strong>${formatted(s.calcMemory)}</strong></p><div class="row"><button class="btn secondary" data-key="RCL">Recall</button><button class="btn secondary" data-key="MC">Clear</button><button class="btn secondary" data-key="M+">Add result</button></div>`;
  if(t==='Trigonometry')return `<p class="muted">Use the main keypad’s sin, cos, tan and Shift for inverse functions. Current angle mode: <strong>${s.calcAngle}</strong>.</p><p class="footnote">Press CA to return to the keypad.</p>`;
  if(t==='Scientific Constants')return constantsPanel(s);
  if(t==='Metric Conversions')return converter(s);
  return '<p class="muted">Select a tool.</p>'
}
const panel=(s,name)=>{s.calcPanel=name;s.calcMenuIndex=0;s.calcShift=false;s.calcAlpha=false};
const variableKey=key=>({ '(-)':'A','°′″':'B',hyp:'C','sin(':'D','cos(':'E','tan(':'F',')':'X','F↔D':'Y','M+':'M'})[key];
const numberOptions=s=>({angle:s.calcAngle,ans:Number(s.calcAnswer)||0,x:s.calcVariables.X,variables:s.calcVariables});
function displayBaseValue(s){if(s.calcBaseValue===undefined)return;let base={DEC:10,HEX:16,BIN:2,OCT:8}[s.calcBase],digits=s.calcBaseValue.toString(base).toUpperCase(),negative=digits.startsWith('-');if(negative)digits=digits.slice(1);let blocks=digits.match(/.{1,8}(?=(.{8})*$)/g)||[digits];s.calcBaseBlock%=blocks.length;s.calcAnswer=(negative?'-':'')+blocks[blocks.length-1-s.calcBaseBlock];s.calcSecondary=`${s.calcBase}${blocks.length>1?' · block '+(s.calcBaseBlock+1)+'/'+blocks.length:''}`}
function insertText(s,value){s.calcStatements=null;if(s.calcMode==='BASE')s.calcBaseValue=undefined;if(s.calcTemplate){let t=s.calcTemplate,text=t.fields[t.field],p=t.cursor;t.fields[t.field]=text.slice(0,p)+value+text.slice(s.calcInsertMode?p:p+value.length);t.cursor=p+value.length;return}
  let text=s.calcExpression,p=Math.min(s.calcCursor,text.length);s.calcExpression=text.slice(0,p)+value+text.slice(s.calcInsertMode?p:p+value.length);s.calcCursor=p+value.length;s.calcReplayIndex=-1;s.calcPanel='display'}
function deleteText(s){if(s.calcTemplate){let t=s.calcTemplate,p=t.cursor,v=t.fields[t.field];t.fields[t.field]=v.slice(0,Math.max(0,p-1))+v.slice(p);t.cursor=Math.max(0,p-1);return}let p=Math.min(s.calcCursor,s.calcExpression.length),width=/\^[23]$/.test(s.calcExpression.slice(p-2,p))?2:1;s.calcExpression=s.calcExpression.slice(0,Math.max(0,p-width))+s.calcExpression.slice(p);s.calcCursor=Math.max(0,p-width)}
function startTemplate(s,kind){let fields=Object.fromEntries(templateFields[kind].map(name=>[name,''])),first=templateFields[kind][0];if(kind==='power'&&s.calcExpression){fields.base=s.calcExpression;first='exponent'}if(kind==='fraction'&&s.calcExpression){fields.numerator=s.calcExpression;first='denominator'}s.calcTemplate={kind,fields,field:first,cursor:0};s.calcExpression='';s.calcCursor=0;s.calcAnswer='0';s.calcPanel='display'}
function completeCalculation(s){try{let expression=s.calcExpression,n;if(s.calcTemplate){let t=s.calcTemplate;if(Object.values(t.fields).some(v=>!v))throw Error('Fill every □ box');if(t.kind==='integral'){let a=evaluateExpression(t.fields.lower,numberOptions(s)),b=evaluateExpression(t.fields.upper,numberOptions(s));n=integrate(t.fields.body,a,b,numberOptions(s));expression=`∫[${t.fields.lower},${t.fields.upper}] ${t.fields.body} dx`}
      else if(t.kind==='derivative'){let x=evaluateExpression(t.fields.at,numberOptions(s));n=differentiate(t.fields.body,x,numberOptions(s));expression=`d/dx ${t.fields.body} at x=${t.fields.at}`}
      else{let f=name=>evaluateExpression(t.fields[name],numberOptions(s));if(t.kind==='fraction')n=f('numerator')/f('denominator');if(t.kind==='power')n=f('base')**f('exponent');if(t.kind==='nthroot')n=Math.sign(f('radicand'))*Math.abs(f('radicand'))**(1/f('index'));if(t.kind==='squareRoot')n=Math.sqrt(f('radicand'));if(t.kind==='cubeRoot')n=Math.cbrt(f('radicand'));if(t.kind==='tenpow')n=10**f('exponent');if(t.kind==='epow')n=Math.exp(f('exponent'));if(t.kind==='logbase')n=Math.log(f('value'))/Math.log(f('base'));expression=t.kind+' '+Object.values(t.fields).join(',')}}
      else{if(!expression)throw Error('Enter an expression');if(s.calcMode==='BASE'){let base={DEC:10,HEX:16,BIN:2,OCT:8}[s.calcBase];s.calcBaseValue=evaluateBaseExpression(expression,base);s.calcBaseBlock=0;displayBaseValue(s);s.calcHistory.unshift({expression,answer:s.calcAnswer});s.calcHistory=s.calcHistory.slice(0,30);return}
      if(s.calcMode==='CPLX'&&expression.includes('∠')){let parts=expression.split('∠');if(parts.length!==2)throw Error('Enter r∠θ');let r=evaluateExpression(parts[0],numberOptions(s)),theta=evaluateExpression(parts[1],numberOptions(s)),rad=s.calcAngle==='DEG'?theta*Math.PI/180:s.calcAngle==='GRAD'?theta*Math.PI/200:theta,real=r*Math.cos(rad),imag=r*Math.sin(rad);if(Math.abs(real)<1e-12)real=0;if(Math.abs(imag)<1e-12)imag=0;s.calcAnswer=`${formatted(real)} ${imag<0?'−':'+'} ${formatted(Math.abs(imag))}i`;s.calcSecondary='CPLX';s.calcHistory.unshift({expression,answer:s.calcAnswer});s.calcHistory=s.calcHistory.slice(0,30);return}
      if(expression.includes(':')){let statements=expression.split(':').map(v=>v.trim());if(statements.some(v=>!v))throw Error('Complete each statement');s.calcStatements={entries:statements,index:0};expression=statements[0]}
      if(/(?:^|[^a-z])i\b/i.test(expression)){let [re,im]=evaluateComplexExpression(expression,numberOptions(s));s.calcAnswer=im===0?formatted(re):`${formatted(re)} ${im<0?'−':'+'} ${formatted(Math.abs(im))}i`;s.calcSecondary='';s.calcHistory.unshift({expression,answer:s.calcAnswer});s.calcHistory=s.calcHistory.slice(0,30);return}n=evaluateExpression(expression,numberOptions(s))}
    s.calcAnswer=formatted(n);s.calcEngExp=null;s.calcSecondary=s.calcStatements?`Disp ${s.calcStatements.index+1}/${s.calcStatements.entries.length}`:/^(?:Pol|Rec)\(/i.test(expression)?'Y = '+formatted(s.calcVariables.Y):'';s.calcHistory.unshift({expression,answer:s.calcAnswer,template:s.calcTemplate?structuredClone(s.calcTemplate):null});s.calcHistory=s.calcHistory.slice(0,30);s.calcReplayIndex=-1
  }catch(e){s.calcAnswer='Error: '+e.message}}
function selectMenu(s){let index=s.calcMenuIndex;if(s.calcPanel==='mode'){calculatorSelectMode(s,modes[index]);return}
  if(s.calcPanel==='clear'){clearCalculatorData(s,['Expression','Memory','History','All'][index]);panel(s,'display');return}
  if(s.calcPanel==='setup'){s.calcAngle=['RAD','DEG','GRAD'][index];panel(s,'display');return}
  if(s.calcPanel==='apps'){let name=apps[index][0];s.calcTool=name;s.calcToolResult='';panel(s,name==='Scientific Constants'?'constants':name==='Metric Conversions'?'converter':name==='History'?'history':'tool');return}
  if(s.calcPanel==='history'&&s.calcHistory[index]){let h=s.calcHistory[index];s.calcExpression=h.template?'':h.expression;s.calcTemplate=h.template?structuredClone(h.template):null;s.calcCursor=s.calcExpression.length;s.calcAnswer=h.answer;panel(s,'display')}}
export function clearCalculatorData(s,what){initCalculator(s);if(what==='Expression'||what==='All'){s.calcExpression='';s.calcTemplate=null;s.calcCursor=0;s.calcAnswer='0'}if(what==='Memory'||what==='All'){s.calcMemory=0;s.calcVariables={A:0,B:0,C:0,D:0,E:0,F:0,X:0,Y:0,M:0}}if(what==='History'||what==='All')s.calcHistory=[]}
function factorText(n){if(!Number.isSafeInteger(n)||n<2)throw Error('Prime factors require an integer ≥ 2');let factors=[];for(let p=2;p*p<=n;p+=(p===2?1:2))while(n%p===0){factors.push(p);n/=p}if(n>1)factors.push(n);return factors.join(' × ')}
function equationKey(s,key){let e=s.calcEquation;if(s.calcPanel==='eqmenu'){if(/^[1-6]$/.test(key)){calculatorChooseEquation(s,equationTypes[Number(key)-1].id);return}if(key==='='){calculatorChooseEquation(s,equationTypes[s.calcMenuIndex].id);return}if(key==='Mode'){panel(s,'mode');return}return}
  if(s.calcPanel==='eqresult'){if(key==='='||key==='▶'){e.solutionIndex=(e.solutionIndex+1)%e.solutions.length;return}if(key==='CA'||key==='DEL'){s.calcPanel='eqedit';return}return}
  if(key==='CA'){panel(s,'eqmenu');return}if(key==='Mode'){panel(s,'mode');return}
  if(key==='='||key==='CALC'){if(key==='='&&e.index<e.values.length-1){e.index++;e.cursor=e.values[e.index].length;return}try{let values=e.values.map(value=>{if(!value.trim())throw Error('Fill every □ coefficient');return evaluateExpression(value,numberOptions(s))});e.solutions=solveSelectedEquation(e.type,values);e.solutionIndex=0;s.calcPanel='eqresult'}catch(error){s.calcAnswer='Error: '+error.message}return}
  let value=e.values[e.index],p=e.cursor;if(key==='DEL'){e.values[e.index]=value.slice(0,Math.max(0,p-1))+value.slice(p);e.cursor=Math.max(0,p-1);return}
  if(key==='(-)'){e.values[e.index]=value.startsWith('-')?value.slice(1):'-'+value;e.cursor=e.values[e.index].length;return}
  let insert=/^[0-9.]$/.test(key)?key:key==='−'?'-':key==='a/b'?'/':null;if(insert!==null){e.values[e.index]=value.slice(0,p)+insert+value.slice(p);e.cursor=p+insert.length}}
export function pressCalculatorKey(s,key){initCalculator(s);
  if(key==='ON'){s.calcPower=true;panel(s,'display');return}
  if(s.calcPower===false)return;
  if(key==='Shift'){s.calcShift=!s.calcShift;s.calcAlpha=false;return}
  if(key==='Alpha'){s.calcAlpha=!s.calcAlpha;s.calcShift=false;return}
  if(['eqmenu','eqedit','eqresult'].includes(s.calcPanel)){equationKey(s,key);return}
  if(key==='CA'||key==='AC'){if(s.calcShift){s.calcPower=false;s.calcShift=false;return}s.calcTemplate=null;s.calcExpression='';s.calcAnswer='0';s.calcSecondary='';s.calcEngExp=null;s.calcCursor=0;s.calcPending='';s.calcStatements=null;s.calcBaseValue=undefined;panel(s,'display');return}
  if(s.calcPending){let variable=variableKey(key);if(!variable){s.calcAnswer='Select an Alpha variable (A–F, X, Y, M)';return}if(s.calcPending==='STO'){s.calcVariables[variable]=Number(s.calcAnswer)||0;if(variable==='M')s.calcMemory=s.calcVariables.M}else insertText(s,variable);s.calcPending='';s.calcAlpha=false;s.calcShift=false;return}
  if(s.calcPanel==='mode'||s.calcPanel==='apps'||s.calcPanel==='setup'||s.calcPanel==='history'||s.calcPanel==='clear'){if(key==='='){selectMenu(s);return}if(key==='Apps'||key==='Mode'){panel(s,'display');return}}
  const shifted=s.calcShift,alpha=s.calcAlpha;s.calcShift=false;s.calcAlpha=false;
  if(alpha){if(key==='CALC'){insertText(s,'=');return}if(key==='x⁻¹'){insertText(s,':');return}if(key==='log('){startTemplate(s,'logbase');return}let variable=variableKey(key);if(variable){insertText(s,variable);return}if(key==='EXP'){insertText(s,'e');return}if(key==='ENG'){insertText(s,'i');return}if(key==='.') {insertText(s,'irand(');return}s.calcAnswer='No Alpha function on this key';return}
  if(key==='Mode'){panel(s,shifted?'setup':'mode');return}
  if(key==='Apps'){panel(s,'apps');return}
  if(key==='CONV'){panel(s,shifted?'constants':'converter');return}
  if(s.calcMode==='BASE'){let baseKeys={'a/b':'DEC','√(':'HEX','xʸ':'BIN','x²':'OCT'};if(baseKeys[key]){s.calcBase=baseKeys[key];s.calcBaseBlock=0;displayBaseValue(s);return}if(key==='ln('){s.calcBaseBlock++;displayBaseValue(s);return}if(['.','EXP','sin(','cos(','tan('].includes(key)){s.calcAnswer='Not available in BASE mode';return}}
  if(key==='CALC'){if(shifted){try{let guess=s.calcVariables.X||0,expr=s.calcExpression.split('=');let f=x=>evaluateExpression(expr[0],{...numberOptions(s),x})-(expr[1]?evaluateExpression(expr[1],{...numberOptions(s),x}):0);for(let i=0;i<35;i++){let y=f(guess),der=(f(guess+1e-5)-f(guess-1e-5))/2e-5;if(Math.abs(y)<1e-10)break;if(!der)throw Error('Cannot find a root');guess-=y/der}if(!Number.isFinite(guess)||Math.abs(f(guess))>1e-6)throw Error('No root near X');s.calcVariables.X=guess;s.calcAnswer='X = '+formatted(guess)}catch(e){s.calcAnswer='Error: '+e.message}}else completeCalculation(s);return}
  if(key==='∫dx'){if(s.calcMode==='CPLX'&&!shifted)insertText(s,'∠');else startTemplate(s,shifted?'derivative':'integral');return}
  if(key==='DEL'){if(shifted){s.calcInsertMode=!s.calcInsertMode;return}deleteText(s);return}
  if(key==='RCL'){s.calcPending=shifted?'STO':'RCL';s.calcAlpha=true;return}
  if(key==='MC'){s.calcMemory=0;s.calcVariables.M=0;return}
  if(key==='M+'){let n=Number(s.calcAnswer);if(!Number.isFinite(n)){s.calcAnswer='Error: Calculate a number first';return}s.calcMemory+=(shifted?-n:n);s.calcVariables.M=s.calcMemory;return}
  if(key==='='){if(s.calcPanel!=='display'){panel(s,'display');return}if(s.calcStatements&&s.calcStatements.index<s.calcStatements.entries.length-1){s.calcStatements.index++;try{s.calcAnswer=formatted(evaluateExpression(s.calcStatements.entries[s.calcStatements.index],numberOptions(s)));s.calcSecondary=s.calcStatements.index===s.calcStatements.entries.length-1?'':`Disp ${s.calcStatements.index+1}/${s.calcStatements.entries.length}`}catch(e){s.calcAnswer='Error: '+e.message}return}completeCalculation(s);return}
  if(key==='F↔D'){s.calcFraction=!s.calcFraction;return}
  if(key==='hyp'){s.calcHyp=!s.calcHyp;return}
  if(key==='°′″'){if(shifted){try{s.calcAnswer=factorText(Number(s.calcAnswer))}catch(e){s.calcAnswer='Error: '+e.message}return}let n=Number(s.calcAnswer);if(!Number.isFinite(n))return;if(s.calcDms){s.calcAnswer=formatted(s.calcDms);s.calcDms=null}else{s.calcDms=n;let a=Math.abs(n),d=Math.floor(a),m=Math.floor((a-d)*60),sec=((a-d)*60-m)*60;s.calcAnswer=`${n<0?'−':''}${d}° ${m}′ ${formatted(sec)}″`}return}
  if(key==='ENG'){let n=Number(s.calcAnswer);if(!Number.isFinite(n)||n===0)return;let exp=(s.calcEngExp??Math.floor(Math.log10(Math.abs(n))/3)*3)+(shifted?-3:0);s.calcEngExp=exp;s.calcAnswer=formatted(n/10**exp)+'E'+exp;return}
  if(shifted&&key==='9'){panel(s,'clear');return}
  if(shifted&&key==='0'){let n=Number(s.calcAnswer);if(Number.isFinite(n))s.calcAnswer=formatted(Math.round(n));return}
  if(shifted&&key==='a/b'){s.calcMixedFraction=!s.calcMixedFraction;s.calcFraction=true;return}
  if(shifted&&key==='Ans'){s.calcAngle=s.calcAngle==='RAD'?'DEG':s.calcAngle==='DEG'?'GRAD':'RAD';return}
  if(key==='a/b'&&!shifted&&!s.calcTemplate){startTemplate(s,'fraction');return}
  if(key==='xʸ'&&!shifted&&!s.calcTemplate){startTemplate(s,'power');return}
  if(key==='xʸ'&&shifted&&!s.calcTemplate){startTemplate(s,'nthroot');return}
  if(key==='√('&&!shifted&&!s.calcTemplate){startTemplate(s,'squareRoot');return}
  if(key==='√('&&shifted&&!s.calcTemplate){startTemplate(s,'cubeRoot');return}
  if(key==='log('&&shifted&&!s.calcTemplate){startTemplate(s,'tenpow');return}
  if(key==='ln('&&shifted&&!s.calcTemplate){startTemplate(s,'epow');return}
  const shiftedInsert={'x⁻¹':'!','√(':'cbrt(','xʸ':'root(','x²':'^3','log(':'10^(','ln(':'e^(','sin(':'asin(','cos(':'acos(','tan(':'atan(','(':'%',')':',','×':'nPr','÷':'nCr','+':'Pol(','−':'Rec(','.':'rand()','EXP':'pi'};
  const ordinary={'×':'*','÷':'/','−':'-','(-)':'-','x²':'^2','x⁻¹':'^(-1)','xʸ':'^','a/b':'/','EXP':'E','Ans':'Ans','Abs(':'abs(','√(':'sqrt('};
  let insert=shifted&&shiftedInsert[key]!==undefined?shiftedInsert[key]:(ordinary[key]??key);
  if(s.calcHyp&&['sin(','cos(','tan('].includes(key)){insert=shifted?`a${key.slice(0,-1)}h(`:key.replace('(','h(');s.calcHyp=false}
  insertText(s,insert)
}
export function calculatorControl(s,direction){initCalculator(s);if(s.calcPower===false)return;
  if(s.calcPanel==='eqresult'){let e=s.calcEquation;e.solutionIndex=(e.solutionIndex+(direction==='left'||direction==='up'?-1:1)+e.solutions.length)%e.solutions.length;return}
  if(s.calcPanel==='eqedit'){let e=s.calcEquation,v=e.values[e.index];if(direction==='left'&&e.cursor>0){e.cursor--;return}if(direction==='right'&&e.cursor<v.length){e.cursor++;return}let def=equationTypes.find(x=>x.id===e.type),columns=def.variables?def.variables.length+1:1,delta=direction==='up'?-columns:direction==='down'?columns:direction==='left'?-1:1;e.index=Math.max(0,Math.min(e.values.length-1,e.index+delta));e.cursor=direction==='left'?e.values[e.index].length:Math.min(e.cursor,e.values[e.index].length);return}
  if(['apps','mode','setup','history','clear','eqmenu'].includes(s.calcPanel)){let count=s.calcPanel==='apps'?apps.length:s.calcPanel==='mode'?modes.length:s.calcPanel==='setup'?3:s.calcPanel==='clear'?4:s.calcPanel==='eqmenu'?equationTypes.length:s.calcHistory.length;if(!count)return;let cols=['apps','mode','clear','eqmenu'].includes(s.calcPanel)?2:1,delta=direction==='up'?-cols:direction==='down'?cols:direction==='left'?-1:1;s.calcMenuIndex=Math.max(0,Math.min(count-1,s.calcMenuIndex+delta));return}
  if(s.calcPanel!=='display'){if(direction==='left')panel(s,'display');return}
  if(s.calcTemplate){let t=s.calcTemplate,fields=templateFields[t.kind],i=fields.indexOf(t.field),value=t.fields[t.field];if(direction==='left'&&t.cursor>0){t.cursor--;return}if(direction==='right'&&t.cursor<value.length){t.cursor++;return}let next;if(t.kind==='integral'&&direction==='up')next=t.field==='lower'?1:t.field==='body'?1:1;else if(t.kind==='integral'&&direction==='down')next=t.field==='upper'?0:t.field==='lower'?2:2;else next=direction==='up'?Math.max(0,i-1):direction==='down'?Math.min(fields.length-1,i+1):direction==='left'?Math.max(0,i-1):Math.min(fields.length-1,i+1);t.field=fields[next];t.cursor=direction==='left'?t.fields[t.field].length:Math.min(t.cursor,t.fields[t.field].length);return}
  if(direction==='left'){let p=s.calcCursor;s.calcCursor=Math.max(0,p-(/\^[23]$/.test(s.calcExpression.slice(p-2,p))?2:1))}
  if(direction==='right'){let p=s.calcCursor;s.calcCursor=Math.min(s.calcExpression.length,p+(/^\^[23]/.test(s.calcExpression.slice(p,p+2))?2:1))}
  if(direction==='up'||direction==='down'){let next=s.calcReplayIndex+(direction==='up'?1:-1);if(next>=0&&next<s.calcHistory.length){s.calcReplayIndex=next;let h=s.calcHistory[next];s.calcExpression=h.template?'':h.expression;s.calcTemplate=h.template?structuredClone(h.template):null;s.calcCursor=s.calcExpression.length;s.calcAnswer=h.answer}else if(next<0)s.calcReplayIndex=-1}
}
export function runCalculatorOperation(s,op){initCalculator(s);let v=k=>Number(s.calcInputs[k]),input=k=>s.calcInputs[k]||'',output;
  try{
    if(op==='clear-history'){s.calcHistory=[];s.calcToolResult='History cleared';return}
    if(op==='swap-units'){let a=s.calcInputs.from,b=s.calcInputs.to;s.calcInputs.from=b;s.calcInputs.to=a;return}
    if(op==='convert'){let category=input('category')||'Length',names=Object.keys(units[category]);output=formatted(convertUnits(v('value'),category,input('from')||names[0],input('to')||names[1]));s.calcToolResult=output+' '+(input('to')||names[1]);return}
    if(op.startsWith('matrix-')){let A=parseMatrix(input('matrixA'));let type=op.slice(7);output=type==='determinant'?determinant(A):type==='inverse'?inverse(A):type==='transpose'?transpose(A):multiplyMatrices(A,parseMatrix(input('matrixB')));s.calcToolResult=Array.isArray(output)?matrixText(output):formatted(output);return}
    if(op.startsWith('vector-')){let type=op.slice(7),A=parseVector(input('vectorA')),B=type==='magnitude'?[]:parseVector(input('vectorB'));output=vectorOperation(A,B,type);s.calcToolResult=Array.isArray(output)?output.map(formatted).join(', '):formatted(output);return}
    if(op.startsWith('complex-')){let [re,im]=complexOperation([v('a'),v('b')],[v('c'),v('d')],op.slice(8));s.calcToolResult=`${formatted(re)} ${im<0?'−':'+'} ${formatted(Math.abs(im))}i`;return}
    if(op==='calculate-tool'){
      if(s.calcTool==='Integration')output=integrate(input('expression'),v('a'),v('b'),{angle:s.calcAngle});
      if(s.calcTool==='Differentiation')output=differentiate(input('expression'),v('point'),{angle:s.calcAngle});
      if(s.calcTool==='Statistics'){let x=statistics(input('dataset'));s.calcToolResult=`n=${x.n} · Σx=${formatted(x.sum)} · mean=${formatted(x.mean)} · median=${formatted(x.median)} · σ=${formatted(x.populationSD)} · s=${formatted(x.sampleSD)}`;return}
      if(s.calcTool==='Equation Solver'){let roots=solvePolynomial(v('a'),v('b'),v('c'));s.calcToolResult='x = '+roots.map(r=>typeof r==='number'?formatted(r):r).join(' ; ');return}
      if(s.calcTool==='Table'){let start=v('start'),end=v('end'),step=v('step');if(!step||Math.sign(end-start)!==Math.sign(step)&&end!==start)throw Error('Use a step toward the end value');let count=Math.floor((end-start)/step)+1;if(count<1||count>20)throw Error('Choose 1 to 20 rows');s.calcToolResult=Array.from({length:count},(_,i)=>{let x=start+i*step;return `x=${formatted(x)} → ${formatted(evaluateExpression(input('expression'),{x,angle:s.calcAngle}))}`}).join('  |  ');return}
      s.calcToolResult=formatted(output);return
    }
  }catch(e){s.calcToolResult='Error: '+e.message}
}
